[icon]
prepend_conds = [
	{ if = "hidden & dir",  text = "👻" },  # Hidden directories
	{ if = "dir",           text = "📁" },  # Directories
	{ if = ".rs",           text = "📁" },  # Directories
	{ if = "!(dir | link)", text = "📄" },  # Normal files (not directories or symlinks)
]

exts = [
	{ name = "rs", text = "🦀" },
	{ name = "nim", text = "" },
	{ name = "py", text = "" },
]
