#!/bin/bash 

# This script makes a .txt ascii version of every png in ./ and makes an output in ./ to place them
# Must have Jp2a installed

for file in *.jpg
do
	jp2a "$file" --color -f --term-fit --background=dark | cat > ./"$file".txt
done
