#!/bin/bash


args="$1"  # Start with the first argument
shift  # Shift the arguments to exclude the first one

for var in "$@"; do
    args+="+$var"
done

# Invoke the ESRGAN script with the concatenated arguments
~/Media/ESRGAN/upscale.py $args -fp16 -v -se -s mirror -am bg_difference

# Rename PNG files in the output directory
for file in ./output/*.png; do
    base=$(basename "$file")
    dirname=$(dirname "$file")

    # Remove "models/" prefix from each argument
    arg_name="${args//models\//}"

    new_name="${arg_name}_${base}"
    mv "$file" "$dirname/$new_name"
done
