#!/bin/bash

read -p "Enter number of horizontal splits : " XSCALE
read -p "Enter number of vertical splits : " YSCALE
X=$(identify -format '%w' $1)
Y=$(identify -format '%h' $1)
echo $X
NAME="$(basename -- "$1")"


NEWX=$(( $X/$XSCALE))
NEWY=$(($Y/$YSCALE))
echo $NEWX

RES=""$NEWX"x"$NEWY""

convert $1 -crop $RES +repage +adjoin $NAME%d.png
